from diccionarios.base import DiccionarioSpec
from diccionarios.registry import register


register(
    DiccionarioSpec(
        id="rm_atenciones_a01",
        nombre="RM-Atenciones-A01",
        tipo="rm",
        descripcion="Atenciones del período de análisis",
        required_core_columns=[
            "HOSP_Code",
            "NombreEstablecimiento",
            "NombreLocal",
            "NumeroEpisodio",
            "EstadoEpisodio",
            "Prevision",
            "PlanSalud",
            "IdAtención",
            "EstadoAtencion",
            "IDPaciente",
            "RutPaciente",
            "FechaNacimiento",
            "SexoPaciente",
            "FechaAtencion",
        ],
        recommended_columns=[
            "TipoEpisodio",
            "ProgramaSalud",
            "TipoAtención",
            "NombrePaciente",
            "ApellidoPaterno",
            "ApellidoMaterno",
            "Flag_Beneficiario",
            "Flag_Migrante",
        ],
        optional_patterns=[
            "_Desc",
            "Madre",
            "Lactancia",
            "TipoControl",
        ],
        known_aliases={
            "IdAtencion": "IdAtención",
            "IDAtencion": "IdAtención",
            "Id_Atencion": "IdAtención",
            "NroEpisodio": "NumeroEpisodio",
            "Nro_Episodio": "NumeroEpisodio",
        },
        orden_columnas=[
            "_archivo_origen",
            "HOSP_Code",
            "NombreEstablecimiento",
            "NombreLocal",
            "NumeroEpisodio",
            "EstadoEpisodio",
            "TipoEpisodio",
            "ProgramaSalud",
            "Prevision",
            "PlanSalud",
            "IdAtención",
            "EstadoAtencion",
            "TipoAtención",
            "IDPaciente",
            "RutPaciente",
            "NombrePaciente",
            "ApellidoPaterno",
            "ApellidoMaterno",
            "FechaNacimiento",
            "SexoPaciente",
            "FechaAtencion",
            "Flag_Beneficiario",
            "Flag_Migrante",
        ],
        allow_extra_columns=True,
        min_required_match=0.6,
        crear_columnas_faltantes=True,
    )
)

